# Generated by Django 3.1 on 2020-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividendos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=6, max_digits=100000000)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.IntegerField()),
                ('fecha', models.DateField(unique=True)),
                ('Valor', models.DecimalField(decimal_places=6, max_digits=100000000)),
            ],
        ),
    ]
